In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import constants 
from scipy.special import comb
import scipy.special as ss

In [35]:
#https://www.geeksforgeeks.org/scipy-integration/

In [3]:
print(constants.liter)

0.001


In [4]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [23]:
##special fxns

# combinations of 4
#we can use ss as cited above or import requred fxn like comb or exp etc
print([comb(4,1),comb(4,2),comb(4,3),comb(4,4),comb(4,5)])
print([ss.comb(4,1),ss.comb(4,2),ss.comb(4,3),ss.comb(4,4),ss.comb(4,5)])
print([ss.perm(4, 1), ss.perm(4, 2), ss.perm(4, 3), ss.perm(4, 4), ss.perm(4, 5)])

from scipy.special import exp10
for i in range(10):
    print(ss.exp10(i),end=' ')
print()
# 10 to the power of 2
for i in range(10):
    print(exp10(i),end=' ')

[4.0, 6.0, 4.0, 1.0, 0.0]
[4.0, 6.0, 4.0, 1.0, 0.0]
[4.0, 12.0, 24.0, 24.0, 0.0]
1.0 10.0 100.0 1000.0 10000.0 100000.0 1000000.0 10000000.0 100000000.0 1000000000.0 
1.0 10.0 100.0 1000.0 10000.0 100000.0 1000000.0 10000000.0 100000000.0 1000000000.0 

In [26]:
# import exprel
#It is known as the Relative Error Exponential Function.
#It returns the error value for a given variable. If x is near zero, then exp(x) is near 1.
from scipy.special import exprel

# list of elements
arr = [0,1,2,3,4,5]

print(list(map(exprel,arr)))


[1.0, 1.718281828459045, 3.194528049465325, 6.361845641062556, 13.399537508286059, 29.48263182051532]


In [24]:
#It is known as Gamma function. It is the generalized factorial since z*gamma(z) = gamma(z+1) and gamma(n+1) = n!, for a natural number ‘n’.
print([ss.gamma(56), ss.gamma(156), ss.gamma(0),ss.gamma(1), ss.gamma(5)])

from scipy.special import logsumexp
#It is known as Log Sum Exponential Function. It will return the log of the sum of the exponential of input elements.
# logsum exp of numbers from
# 1 to 10
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# logsum exp of numbers from
# 10 to 15
b = [10, 11, 12, 13, 14, 15]
print([logsumexp(a), logsumexp(b)])


[1.2696403353658278e+73, 4.789142901463394e+273, inf, 1.0, 24.0]
[10.45862974442671, 15.456193316018123]


In [27]:
#It is also known as Lambert Function. It calculates the value of W(z) is such that z = W(z) * exp(W(z)) for any complex number z, where W is known as the Lambert Function
# import lambert function
from scipy.special import lambertw

# calculate W value
print([lambertw(1),lambertw(0),lambertw(56),lambertw(68),lambertw(10)])


[(0.5671432904097838+0j), 0j, (2.9451813101206707+0j), (3.0910098540499797+0j), (1.7455280027406994+0j)]


In [37]:
#It is known as Log Sum Exponential Function. It will return the log of the sum of the exponential of input elements.
from scipy.special import logsumexp

# logsum exp of numbers from
# 1 to 10
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = [1, 2, 3]
# logsum exp of numbers from
# 10 to 15
b = [10, 11, 12, 13, 14, 15]
print([logsumexp(a), logsumexp(b)])
print(np.log(np.exp(1)+np.exp(2)+np.exp(3)))

[3.4076059644443806, 15.456193316018123]
3.40760596444438


In [38]:
#integrate
#The function quad is provided to integrate a function of one variable between two points. The points can be  +infinite or – infinite to indicate infinite limits

from scipy.integrate import quad

def f(x):
    return 3*(x**2) + 1.0

I, err = quad(f, 0, 1)
print(I)
print(err)

2.0
2.220446049250313e-14


In [31]:
#This performs Double Integration with 2 arguments. 
from scipy.integrate import dblquad
area = dblquad(lambda x, y: x*y, 0, 0.5,lambda x: 0, lambda x: 1-2*x)

print(area)

(0.010416666666666668, 4.101620128472366e-16)


In [32]:
#Performs integration of n variables
from scipy.integrate import nquad

def f(x, y, z):
    return x*y*z

I = nquad(f, [[0, 1], [0, 5], [0, 5]])
print(I)

(78.12499999999999, 8.673617379884033e-13)


In [49]:
#With the help of scipy.integrate.fixed_quad() method, we can get the computation of a definite integral using fixed order gaussian quadrature
# import scipy.integrate

from scipy import integrate
  
def func(x): 
    return 3*x**3

#using scipy.integrate.fixed_quad() method
# n is the order of integration
gfg = integrate.fixed_quad(func, 1.0, 2.0, n=1)
  
print(gfg)

(10.125, None)


In [34]:
#With the help of scipy.integrate.romberg() method, we can get the romberg integration of a callable function from limit a to b 
# import numpy and scipy.integrate
import numpy as np
from scipy import integrate

f = lambda x: 3*(np.pi)*x**3

# using scipy.integrate.romberg()
g = integrate.romberg(f, 1, 2, show = True)

print(g)

Romberg integration of <function vectorize1.<locals>.vfunc at 0x00000278727D8D30> from [1, 2]

 Steps  StepSize   Results
     1  1.000000 42.411501 
     2  0.500000 37.110063 35.342917 
     4  0.250000 35.784704 35.342917 35.342917 

The final result is 35.34291735288517 after 5 function evaluations.
35.34291735288517


In [42]:
#With the help of scipy.integrate.romb() method, we can get the romberg integration using samples of a function from limit a to b
# import numpy and scipy.integrate
import numpy as np
from scipy import integrate


x = np.arange(0,5)

# using scipy.integrate.romb() method
f = integrate.romb(x)

print(f)


8.0


In [43]:
#numpy.polyint(p, m) : Evaluates the anti – derivative of a polynomial with the specified order.
# Python code explaining
# numpy.polyint()
	
# importing libraries
import numpy as np
	
# Constructing polynomial
p1 = np.poly1d([2,6])
p2 = np.poly1d([4,8])
	
a = np.polyint(p1, 1)
b = np.polyint(p2, 2)

print ("\n\nUsing polyint")
print ("p1 anti-derivative of order = 2 : \n", a)
print ("p2 anti-derivative of order = 2 : \n", b)




Using polyint
p1 anti-derivative of order = 2 : 
    2
1 x + 6 x
p2 anti-derivative of order = 2 : 
         3     2
0.6667 x + 4 x


In [44]:
#With the help of scipy.integrate.cumtrapz() method, we can get the cumulative integrated value of y(x) using composite trapezoidal rule.
# import numpy and scipy.integrate.cumtrapz
import numpy as np
from scipy import integrate

a = np.arange(0, 5)
b = np.arange(0, 5)

# using scipy.integrate.cumtrapz() method
f = integrate.cumtrapz(b, a)

print(f)


[0.5 2.  4.5 8. ]


In [45]:
#numpy.trapz() function integrate along the given axis using the composite trapezoidal rule.
# Python program explaining
# numpy.trapz() function

# importing numpy as geek
import numpy as np

b = [2, 4]
a = [6, 8]

f = np.trapz(b, a)

print(f)


6.0


In [46]:
#With the help of scipy.integrate.simps() method, we can get the integration of y(x) using samples along the axis and composite simpson’s rule
# import numpy and scipy.integrate
import numpy as np
from scipy import integrate

a = np.arange(0, 5)
b = np.arange(0, 5)

# using scipy.integrate.simps() method
f = integrate.simps(b, a)

print(f)


8.0


In [50]:
#linear algebra
#scipy.linalg.solve(a, b, sym_pos, lower, overwrite_a, overwrite_b, debug, check_finite, assume_a, transposed)
# Import the required libraries
from scipy import linalg
import numpy as np

# The function takes two arrays
a = np.array([[7, 2], [4, 5]])
b = np.array([8, 10])

# Solving the linear equations
res = linalg.solve(a, b)
print(res)

[0.74074074 1.40740741]


In [51]:
#scipy.linalg.inv returns the inverse of the square matrix.
# Import the required libraries
from scipy import linalg
import numpy as np

# Initializing the matrix
x = np.array([[7, 2], [4, 5]])

# Finding the inverse of
# matrix x
y = linalg.inv(x)
print(y)

[[ 0.18518519 -0.07407407]
 [-0.14814815  0.25925926]]


In [52]:
#scipy.linalg.pinv returns the pseudo-inverse of the input matrix.
# Import the required libraries
from scipy import linalg
import numpy as np

# Initializing the matrix
x = np.array([[8 , 2] , [3 , 5] , [1 , 3]])

# finding the pseudo inverse of matrix x
y = linalg.pinv(x)
print(y)

[[ 0.14251208 -0.03381643 -0.03864734]
 [-0.07487923  0.16183575  0.11352657]]


In [53]:
#The scipy.linalg.det takes a square matrix A and returns D, the determinant of A. The determinant is a specific property of the linear transformation of a matrix. The determinant of a 2×2 matrix is given by:
# Importing the required libraries

# Initializing the matrix A
A = np.array([[9 , 6] , [4 , 5]])

# Finding the determinant of matrix A
D = linalg.det(A)
print(D)

21.0


In [54]:
#The function scipy.linalg.svd takes a matrix M to decompose and returns:
#A Unitary matrix having left singular vectors as columns.
#The singular values sorted in non-increasing order.
#A unitary matrix having right singular vectors as rows.
# Importing the required libraries

# Initializing the matrix M
M = np.array([[1 , 5] , [6 , 10]])

# Passing the values to the
# eigen function
x , y , z = linalg.svd(M)
print(x , y , z)

[[-0.38684104 -0.92214641]
 [-0.92214641  0.38684104]] [12.62901571  1.58365469] [[-0.46873958 -0.88333641]
 [ 0.88333641 -0.46873958]]


In [55]:
# Initializing the matrix M
M = np.array([[9 , 3] , [2 , 4]])

# Passing the values to the eigen
# function
val , vect = linalg.eig(M)

# Display the Eigen values and Eigen
# vectors
print(val)
print(vect)

[10.+0.j  3.+0.j]
[[ 0.9486833  -0.4472136 ]
 [ 0.31622777  0.89442719]]


In [56]:
#The function scipy.linalg.norm returns one of the seven different matrix norms or one of an infinite number of vector norms. 

#The L2 norm evaluates the distance of the vector coordinate from the origin of the vector space. It is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value.
#The L1 norm is evaluated as the sum of the absolute vector values. It is an evaluation of the Manhattan distance from the origin of the vector space.
# Importing the required libraries

# Initializing the input array
x = np.array([6 , 3])

# Calculating the L2 norm
a = linalg.norm(x)

# Calculating the L1 norm
b = linalg.norm(x , 1)

# Displaying the norm values
print(a)
print(b)

6.708203932499369
9.0


In [57]:
# Initializing the matrix
x = np.array([[16 , 4] , [100 , 25]])

# Calculate and print the matrix
# square root
r = linalg.sqrtm(x)
print(r)
print("\n")

# Calculate and print the matrix
# exponential
e = linalg.expm(x)
print(e)
print("\n")

# Calculate and print the matrix
# sine
s = linalg.sinm(x)
print(s)
print("\n")

# Calculate and print the matrix
# cosine
c = linalg.cosm(x)
print(c)
print("\n")

# Calculate and print the matrix
# tangent
t = linalg.tanm(x)
print(t)


[[ 2.49878019  0.62469505]
 [15.61737619  3.90434405]]


[[2.49695022e+17 6.24237555e+16]
 [1.56059389e+18 3.90148472e+17]]


[[-0.06190153 -0.01547538]
 [-0.38688456 -0.09672114]]


[[ 0.22445296 -0.19388676]
 [-4.84716897 -0.21179224]]


[[0.0626953  0.01567382]
 [0.39184561 0.0979614 ]]


In [58]:
# import numpy library
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)
# print LU decomposition
print(np.dot(L,U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         8.        ]
 [0.         0.85714286 1.85714286]
 [0.         0.         0.5       ]]
[[7. 8. 8.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [59]:
#Solving systems of linear equations can also be done

v = np.array([[2],[3],[5]])
print(v)
s = linalg.solve(A,v)
print(s)

[[2]
 [3]
 [5]]
[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


In [60]:
#SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.
#Lets look on how to construct a large sparse matrix:
# import necessary modules

from scipy import sparse
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))
print(A)
  
A[0,:100] = np.random.rand(100)
A[1,100:200] = A[0,:100]
A.setdiag(np.random.rand(1000))
print(A)


  (0, 0)	0.18984969662977413
  (0, 1)	0.17941253782242217
  (0, 2)	0.6108362418157997
  (0, 3)	0.1327474572875187
  (0, 4)	0.03430245161485734
  (0, 5)	0.28347662830415743
  (0, 6)	0.8115625004660325
  (0, 7)	0.34118961284056704
  (0, 8)	0.6619595150341513
  (0, 9)	0.24527431327577653
  (0, 10)	0.6602622741691258
  (0, 11)	0.5684487807359849
  (0, 12)	0.7690591552755628
  (0, 13)	0.6488883713870968
  (0, 14)	0.2317275147498693
  (0, 15)	0.694718537851711
  (0, 16)	0.778591570312174
  (0, 17)	0.6421757192849356
  (0, 18)	0.7836313312219058
  (0, 19)	0.4674832976008302
  (0, 20)	0.022753720906483088
  (0, 21)	0.3863845801732245
  (0, 22)	0.21516084332623564
  (0, 23)	0.9368726817955622
  (0, 24)	0.4742978819931255
  (0, 25)	0.8620205455424156
  (0, 26)	0.22655043620862358
  (0, 27)	0.7662619232323491
  (0, 28)	0.7190219368331446
  (0, 29)	0.3070489021567727
  (0, 30)	0.7736134826179134
  (0, 31)	0.8575361707353583
  (0, 32)	0.0921103904513011
  (0, 33)	0.05511669002045394
  (0, 34)	0.17